version: '3.4'

services:
#PHP Service
  php74:
    build:
      context: ./docker/web
    container_name: desafio_php74
    tty: true
    working_dir: /var/www/html/desafio
    volumes:
      - ./:/var/www/html/desafio
    networks:
      - bubble
    expose:
      - "9000"

#Nginx Service
  nginx:
    container_name: desafio_nginx
    image: nginx:latest
    stop_signal: SIGQUIT
    stop_grace_period: 90s
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 65080:80
    networks:
      - bubble
    depends_on:
      - php74

networks:
  bubble: