version: '3.9'

volumes:
  vol-db-desafio: 
    external: true

services:
#PHP Service
  php:
    image: app
    build:
      context: ./docker/web
    container_name: desafio_php
    tty: true
    working_dir: /var/www/html/desafio
    volumes:
      - ./:/var/www/html/desafio
      - ./docker/web/supervisord.conf:/etc/supervisor/supervisord.conf
    networks:
      - bubble
    expose:
      - "9000"
    command: ["php-fpm"]

#Nginx Service
  nginx:
    container_name: desafio_nginx
    image: nginx:latest
    stop_signal: SIGQUIT
    stop_grace_period: 90s
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 65080:80
    networks:
      - bubble
    depends_on:
      - php

#Mysql Service
  db:
    container_name: desafio_mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306" 
    volumes:
      - vol-db-desafio:/var/lib/mysql   
    image: mysql:8.0
    networks:
      - bubble

#Phpmyadmin Service
  phpmyadmin:
    container_name: desafio_phpmyadmin
    restart: always
    links:
      - db
    ports:
      - 81:80
    image: phpmyadmin:5.1
    networks:
      - bubble

#RabbitMq Service
  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    container_name: desafio_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - bubble

#Supervisor Service
  supervisor:
    container_name: desafio_supervisor
    image: app
    networks:
      - bubble
    depends_on:
      - php
      - nginx
    command: ["supervisord", "-n", "-c", "/etc/supervisor/supervisord.conf"]
    volumes:
      - ./:/var/www/html/desafio

networks:
  bubble: